.github/workflows/create_ld_project.py, .github/workflows/deploy_files/deploy.yaml, .github/workflows/ld-demoEnv-deployment.yaml, .github/workflows/requirements.txt, .github/workflows/update_k8s_deploy_file.py
=> Testing Provisioning

.github/workflows/delete_ld_project.py, .github/workflows/ld-demoEnv-deprovision.yaml, dockerfile
=> Added deprovision process

.github/workflows/ld-demoEnv-deprovision.yaml
=> Fixed naming

.github/workflows/create_ld_project.py, .github/workflows/ld-demoEnv-deployment.yaml
=> run script on push as well

.github/workflows/ld-booth-deployment.yaml
=> Update booth deployments

.github/workflows/ld-demoEnv-deployment.yaml
=> Update user demoenv on weekends

pages/mobile.tsx
=> Update Mobile Demo

.github/workflows/ld-demoEnv-deprovision.yaml
=> Updated script for delete

.github/workflows/create_migration_flag.py
=> added migration flag

components/ui/airwayscomponents/bookedFlights.tsx, components/ui/infinityloader.tsx
=> Minor fixes

Terraform/metrics.tf
=> added new metrics

.github/workflows/create_metric_group.py, .github/workflows/create_migration_flag.py
=> Added 10 second timer to APIs

.github/workflows/create_metric_group.py, .github/workflows/create_migration_flag.py, .github/workflows/delete_ld_project.py
=> Added logic for rate-limit

.github/workflows/delete_ld_project.py
=> fixed error code

.github/workflows/ld-demoEnv-deployment.yaml, Terraform/templateENV.tf, components/KeyboardNavigation.tsx, components/quickcommand.tsx, components/ui/command.tsx, package-lock.json, package.json, pages/_app.tsx, pages/api/ldreset.ts
=> Added Command Component

.github/workflows/ld-booth-deployment.yaml, .github/workflows/ld-test-deployment.yaml
=> Added Project keys

.github/workflows/create_ld_project.py
=> create context kind

.github/workflows/delete_ld_project.py
=> fix_del_script

.github/workflows/create_ld_project.py, .github/workflows/delete_ld_project.py, Terraform/metrics.tf
=> Fix for audience metrics

.github/workflows/create_ld_project.py
=> fix placement of function

.github/workflows/create_ld_project.py
=> beta api fix

.github/workflows/create_ld_project.py
=> context kind fix

.github/workflows/create_experiment.py, .github/workflows/ld-demoEnv-deployment.yaml
=> added experimentation

.github/workflows/create_experiment.py, components/quickcommand.tsx, components/ui/bankcomponents/stocksCard.tsx, components/ui/bankcomponents/wealthManagement.tsx, components/ui/marketcomponents/experimentgenerator.tsx, pages/_app.tsx, utils/contexts/login.js
=> Added Experiment Generator

Terraform/segments.tf
=> Added segments for template env

.github/workflows/create_experiment.py, components/ui/marketcomponents/experimentgenerator.tsx, utils/contexts/login.js
=> Audience context

components/ui/marketcomponents/experimentgenerator.tsx
=> fixed experiment generator

Terraform/metrics.tf, components/ui/bankcomponents/stocksCard.tsx
=> Changed to Audience Context

.github/workflows/update_all_user_environments.yaml
=> Update all Demo Envs

.github/workflows/update_all_user_environments.yaml
=> Weekly Automation to Update All Demo Envs

.github/workflows/ld-demoEnv-deployment-manual.yaml
=> testing manual workflow

.github/workflows/ld-demoEnv-deployment.yaml
=> Duplicate Process Removed

.github/workflows/ld-demoEnv-deployment-manual.yaml, .github/workflows/ld-demoEnv-deployment.yaml
=> Minor Fixes to GH Actions

.github/workflows/ld-demoEnv-deprovision-manual.yaml, .github/workflows/ld_api/delete_ld_project.py
=> Added manual deprovision script

.github/workflows/ld_api/create_ld_featureflags.py
=> fix description

components/LoginHomePage.tsx, components/ui/airwayscomponents/airlineDestination.tsx, components/ui/airwayscomponents/airlineHero.tsx, components/ui/airwayscomponents/airlineInfoCard.tsx, components/ui/airwayscomponents/airportPicker.tsx, components/ui/airwayscomponents/bookedFlights.tsx, components/ui/airwayscomponents/flightCalendar.tsx, components/ui/airwayscomponents/launchClubStatus.tsx, components/ui/airwayscomponents/launchSignup.tsx, components/ui/avatar.tsx, components/ui/navbar.tsx, pages/airways.tsx, pages/index.tsx, tailwind.config.js, utils/getVariantClassName.js
- standardized airline color to pink purple and blue
- used same gradient variable across airline
- fixed spacing for my booking and factoring code
- change color to standardize pink purple blue for my bookings
- my booking ai insight doesn't clash when switching from desktop to mobile
- added brightness and cursor pointer for all buttons that are pressable. 
- added animate pulse to all buttons related to demo blocks
- fixed launch perk pop up to be centered of hero
- fixed navbar where it is mobile friendly 
- fixed calendar date picker to be pink
- fixed launch club pop up with spacing and factor code
-
=> Tony airline fix

.github/workflows/ld-demoEnv-deployment.yaml
=> testing code references

components/ui/bankcomponents/wealthManagement.tsx
=> fix formating in wealth management card in bank

components/ui/logincomponent.tsx
=> logincompoent update

components/ui/logincomponent.tsx, pages/_app.tsx
=> Fix minor login updates

.github/workflows/ld_api/create_experiment.py, .github/workflows/ld_api/create_ld_featureflags.py, .github/workflows/ld_api/create_ld_metrics.py, Terraform/flags.tf, Terraform/metrics.tf
=> Updated Terraform / Provisioning Files

.github/workflows/ld_api/create_experiment.py
=> update exp script

.github/workflows/ld_api/create_ld_featureflags.py, Terraform/flags.tf, components/ui/marketcomponents/funnelexperimentgenerator.tsx
=> Small fixes 05-15

pages/index.tsx
=> Fix Homepage Reference

.github/workflows/ld_api/create_ld_featureflags.py, .github/workflows/v.1.2.1/cartSuggestedItems.json, .github/workflows/v.1.2.1/release-new-investment-stock-api.json, .github/workflows/v.1.2.1/update-1.2.1.yaml, Terraform/flags.tf, components/ui/airwayscomponents/launchSignup.tsx, components/ui/bankcomponents/stocksCard.tsx, components/ui/marketcomponents/featureexperimentgenerator.tsx, components/ui/marketcomponents/funnelexperimentgenerator.tsx, utils/contexts/login.js
=> 1.2.1 fixes

package-lock.json, package.json
=> update app version

.github/workflows/update-1.2.1.yaml
=> added checks for success and failure

components/personacontext.tsx, components/quicklogindialog.tsx, components/ui/airwayscomponents/bookedFlights.tsx, components/ui/logincomponent.tsx, components/ui/navbar.tsx, tailwind.config.js, utils/contexts/StarterUserPersonas.js
=> Tony button fix

.github/workflows/update-1.2.1.yaml, package-lock.json, package.json
=> fix_update_issue

.github/workflows/ld-add-code-references.yaml
=> added manual code references

.github/workflows/ld-booth-deployment.yaml, .github/workflows/ld-demoEnv-deployment-manual.yaml, .github/workflows/ld-demoEnv-deployment.yaml, .github/workflows/ld-test-deployment.yaml
=> updated branch on code refs

components/ui/airwayscomponents/pickMyDestinationModal.tsx, styles/globals.css
=> updated component

.github/workflows/ld_api/create_ld_project.py, .github/workflows/update_resources/update_ld_project.py
=> fix changes

.github/workflows/ld_api/create_ld_project.py
=> update exp file

.github/workflows/ld_api/create_ld_featureflags.py, .github/workflows/update_resources/releaseAITravelInsights.json, .github/workflows/update_resources/update_ld_project.py
=> fixed_ai_tag

.github/workflows/ld-test-deployment.yaml, .github/workflows/ld_api/create_ld_segments.py, Terraform/segments.tf, package-lock.json, package.json, utils/contexts/login.js
=> Minor Updates

.github/workflows/ld-test-deployment.yaml
=> ld cli update

.github/workflows/ld-test-deployment.yaml
=> update test env name

.github/workflows/ld-test-deployment.yaml, package-lock.json, package.json
=> Fixed test deployment

.github/workflows/demo_provisioning_scripts/DemoBuilder.py
=> added more automation to script

components/chatbot/ChatBot.tsx, components/ui/airwayscomponents/AirwaysHero.tsx, components/ui/airwayscomponents/DestinationPicker.tsx, components/ui/airwayscomponents/bookedFlights.tsx, pages/api/chat.ts, tailwind.config.js, utils/constants.js
added default ai model and prompt when undefined for ai flags. highlighted powered by claude and amazon bedrock
=> Tony airline fix 2

.github/workflows/demo_provisioning_scripts/DemoBuilder.py, .github/workflows/demo_provisioning_scripts/LDPlatform.py, components/chatbot/ChatBot.tsx, components/ui/airwayscomponents/DestinationPicker.tsx, components/ui/airwayscomponents/bookedFlights.tsx, package-lock.json, package.json, pages/api/chat.ts, pages/api/destination-picker.ts, utils/constants.js
- Switched to AI Config (Shadow Flags)
- Removed Meta Llama AI Config (Unsupported Version)
- Made All Feature Flags Client available by default
=> ai config patches

.github/workflows/cloud_demo_app_update_only.yaml
=> Script updates

components/generators/guarded-release-generator/guardedReleaseGenerator.tsx
=> Fixing RG Generator

components/generators/experimentation-automation/featureExperimentGeneratorFunctions.ts, components/generators/experimentation-automation/funnelExperimentGeneratorFunctions.ts
=> Fix Experiment Generators 

components/chatbot/ChatBot.tsx, components/ui/csnav.tsx, package-lock.json, package.json
=> Add ai tracker

.github/workflows/cloud_demo_app_update_only.yaml, package-lock.json
=> Fixed Update File

.github/workflows/cloud_demo_app_update_only.yaml
=> Add variables to update only file

.github/workflows/demo_provisioning_scripts/DemoBuilder.py, .github/workflows/demo_provisioning_scripts/LDGeneratorsRunner.py, .github/workflows/demo_provisioning_scripts/LDPlatform.py, .github/workflows/demo_provisioning_scripts/requirements.txt, .github/workflows/demo_provisioning_scripts/results_generator.py, .github/workflows/old_resources/ld_api/create_ld_metrics.py, .github/workflows/old_resources/update_resources/aiChatbotNegativeFeedback.json, .github/workflows/old_resources/update_resources/aiChatbotPositiveFeedback.json, .github/workflows/requirements.txt, components/chatbot/ChatBot.tsx, components/generators/experimentation-automation/featureExperimentGeneratorFunctions.ts, pages/api/chatbotfeedback.ts
🚀 LaunchDarkly Demo Environment: Generator Automation & Experiment Data
**Summary**
This PR introduces a comprehensive generator system for LaunchDarkly demo environments, including:
- Automated flag, metric, and AI config generation
- Guarded rollout and experiment simulation
- AI config monitoring and experiment results generation
- Proper environment variable handling for subprocesses
✅ Checklist
🏗️ Core Generator System
🧪 Experiment & AI Config Simulation
🛠️ Workflow & Environment
📦 Dependencies
📝 Documentation & Logging
=> Version 2.9

.github/workflows/demo_provisioning_scripts/DemoBuilder.py, pages/api/chat.ts
=> fix model+api call

.github/workflows/demo_provisioning_scripts/DemoBuilder.py
=> Fix AI Config Variations 

.github/workflows/demo_provisioning_scripts/DemoBuilder.py, components/SignUpProvider.tsx, components/generators/experimentation-automation/experimentGeneratorGeneral.tsx, components/generators/experimentation-automation/experimentationConstants.js, components/generators/experimentation-automation/featureExperimentGeneratorFunctions.ts, components/generators/experimentation-automation/funnelExperimentGeneratorFunctions.ts, components/quickcommand.tsx, components/ui/NavComponent/NavbarSignUpInButton.tsx, components/ui/WrapperMain.tsx, components/ui/bankcomponents/SignUpProgressIndicator.tsx, components/ui/bankcomponents/bankHomePage.tsx, debug_output.log, full_debug.log, pages/_app.tsx, pages/personal-details.tsx, pages/services.tsx, pages/signup.tsx, pages/success.tsx, utils/constants.ts, utils/typescriptTypesInterfaceIndustry.ts
- **3 new experiments**: Signup funnel (A6), Special offers (A5), Widget position (A7)
- **Multi-step signup flow**: 4-page flow with state management (migrated from template repo)
- **DemoBuilder.py updates**: All provisioning logic added
- **Branch issue resolved**: work was accidentally done in `govt-update3`, but was then migrated here. Just need you to double check that everything looks in order and all demos were unaffected.
=> ToggleBank Experimentation Integration
